travis:
  secure:
    BINSTAR_TOKEN: 2AW/OPBnqe5YJP9r5kU5nTjYrUX7SF3iYblsp05MfN78dmMGE1tr4qLl+kuh5Fhw17Pbtgq4nfG45TN4H91KMm27a65skbNSaqA6mrRZqWzu7ZLIGq12zZcYrkOgdsepw6PdwgpZmUXAvaLCizsnW8xMtfNLjnI6nb1WqxEpZrnDPBwbEqfpojiPSEVuTUqDdB57/b6t80c8jH8jT0hRyrdB3mO0x8qkIaUyBpjh1NtmMmX3jaL+zLLrU6sf6gU7qZ2TdTGj+paxL03YOT18Mb91N1Hs0ELYqr2PwMgL+9iJASS+Z4/O1OdaJfqYamvZGz5CkVMJpLEcPn9Vmi/t+QTxBXkUZ719maMnYxDMQ8yhJir3HNoxddU3ROH9V0NfWfDNiCJ4bBYuBWu6CRBjZ+0RyS/Phl7n3Rx14gf9UGxlV01GknE6f9r/vkc7I0hfNBdZwBiCmevOBi+6q4Lii9QCs7FxkmNN5Ajyhb31CzsezYKo2MU52bfoToOkD/ZsU1risuQn4bYi3xcNVLDRpQpyvZLbRon4gkdQrRS6sIwTwZ3JnMxNF44LBdnXRiW4i04EkWFgJqX9A7xR4C/kxv053xTAOTy9jaJzeKDB5tUVffaW1q/f2XKZZU/xIVC8junjwbPRYVAAjniEKLR3VqrsjlguywTu+uYKYa3S46I=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
