travis:
  secure:
    BINSTAR_TOKEN: 5mJWguh8yHZTcb0A6XkpJedjEfy7NU6fzDh1AHQO9h3WY7U2iehiD45K66mR5krJKa2U/oHo6FFaRe+p5w5ribA7nO2SUSqqwm9diPm41W6x1KiSz+rt09ZXcANi4fBhbc1LHQJru3YEOU0xdvlA7h2kY4S44PgUhbUe6wn3/vrsJrt9Kq0U1zluQ4DINXPk49Vd/VF87Ls/zJ0Ih9mJpBMl3fFGm8rqOrUpyz9p9cCugx5aMZk6FaJw6HndnsThHf4TQ9zsEdklFQgkfAEGLPikkx7qV2/HJr52UQOIYwKUNFMMztzFOpUYebQeSfuJPhe71zz7cT0N+L8frm3Bfphp9G2ueKdSsqjxJgt0NeKNvpvcP7+ZgkeYSHcuwYZEfsfNyJqN47W2V8RQzY+qtbR9yTPiGR+3vk1Vm9ee3hFHkN0YigWQQ7dIA3CbC1RZjVQMrPACQTsKMfU2gfwQTkbhGwudjdiVCc2bqk6oJmeYOgRznw8+I9wA0AojY1SdAje2hujMEGt46F/50/t+SquWN2gTWGcKI0Rgxfozzj5EqTYhFXsweTXsRDRpQ1B+0tokMw4R58wUrO/THkjWXLt1l31gOC2zsZC01qrEbxe3GgIXt+r2z0bg/dw3fT0t4xOoI2drl1rImTcTlEHg9xXPCS3HK/FbUXRHPKDlFgQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
