travis:
  secure:
    BINSTAR_TOKEN: hjLXhDZuL/ZAlkSQSqzdVEidqICesUXo8orYDbgGvH9yv9l6x1REoyyb9j3+pdUZv4fT0dJLWk9+QKPEem3NLTdLU4mVbfAdOMmUkOafWAu0JxOk9F26c+MmsKX2Bvzv4qBjkt1s1Dxl3kDmrCI0aqjmam6zustuZelyiNb1b9+L/3MIq5YoORxnTICsZ5oANRpxl9PYR/KaXgXgRp++nVDfVa33xOv1Wlczua4Fec8NFzzpwP0rukzBG8aojQOtzy4d7kLj3SzMLKMC0FB1uyrq4ub6q91O2U2Kxnr3jH6C4zota42KeetVWXHr5GMh4gHYbdTNMRg/3dH81JKWT6RHF86Lac82RAfYyyJCQCb9XujCHJqr/Sb4IpkrlJyaEssGcrC1ITxcfaQINKnyKf43SgOTNw+qpJcdXFYbAdjBokEYi22XTNDMXJF5eBtEN42Q2TC62f21s1HnGVN4VqPqBeQRlSR/Ki3229MqspbzNOFugF0lv7Vn7cJXp7j2oqjvmcvMqEO/ycjXbgmkxgaRoDPkKLjREcqlm+T+8jqp9KKbNaHgCFlB0ukZysict0D4arqicmWg9UxOdl+p/WnDe0EmU6RaCc0PhyatbwOn43Mf5VwZwv0U8jqEPpTdb6G9ujSRO8sY/Q/AcsQ1IhYSLKtEPuHbtJF8bcN0/ag=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
