travis:
  secure:
    BINSTAR_TOKEN: elqVd9Y2gMFz2fz6PXa3hknU1dXZ6zKTeIx0mVeO5pQJjQkiGnLZe5EbrdbZaSH2d2jnz6g7B7s+j2Pt1q+ZRbTFVGaC0kHCJEwqu+6xpN1s8VdducacKJ5oU/AAgEfwTSjMjGLA0T1kSW8ro5uxN4dgM9502TgO6VYS/kBjGYU/noEW7cs6SBLx2rSQblgO1nm7y8f5vtpWSqnwPOf5GzIW4INt7DX6aWlOdkHeFi/7SmVeAPFuWXM1M4l7ypBqOIO7cKOw3HROnJv60bLpXuWoWKJdEL0bflskCQFLge95TUky7cFtmeO334dBplVsefmWPlRauOLOIn/PtqEHs8ciQnSZZD7gvlXTM1NkPQ82nV01hfV8tYrKceie90tIvw5QCaepqA69b+I+r3vATdNqwehAYrsB7oXJSWCLyJ/kE0TnXuJuPAXsdjMGz+nGmne0ta0yyVRKjNM9NdeKQgNNTj/8Qowj4RruqaEj+o2xZk/HCgDJepCopl0In2uu4kky01tdsE2UHrytYBrHWbrea1GWEOPJ9wpFi+1LMFOKCIvs/riJzMRgYKWRiRVlt+tT1V1BnrpHuJRt/6sWBaTDfzkW5+TPtfGDl2v0AiSolt+bSCgtY5WVVJk0M3lHf6Gx+PfUc/5kUmSlcCmVTR56tXu3M34w9yKkeCVzVGQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
