travis:
  secure:
    BINSTAR_TOKEN: GxK4k2Unk1jzVe/+nk4su4naUaN7WEtQ+4w/l3YGXvD1Qb9fYFZtre14F2P2qTqGGjdNZajUQGE3bTw36RQnD0v962yIjutWmQcFsUJ1DM8XHaPnQ7qLdj23XwPpEAO7Ykh6Ve7eGQ0uXfU34APrVbGSqhZfVBi1sPA3YI0L1wb+C+KPE801j5nvTDE9M11Ubi6tNKrH3dhhIyEYdvF7PQizMeN9ZiBZpigBB+qMMIdS9R9jlH/ugq2dbWOB5owwTSCHI/i0L5LidUQWgwvcSxiMsds3VI9dGQv/ItqxvdotkKTIKtKpKLAtC4ATFjLdqiJ1eTMCmsvc3ypNe5YOYvW6aQQ3LQtwejytmF1LQJyf9lO1UT9gW+PlvvbUkPteTXO4zn06ZELy7Lr8OfZQGXl8+J7ART3jXgx8HESbmhx5fzMPULE9F7nK4Hf604SQ+JtVhgI7M5ke3yuBiU11gmVPkVcOvuJCws5JfBSuwTyhPK9RQQ5R7VHeoHPd04MkbGwgX6NGcgMmCY/pI+O29SWDXvySqNGXVMM6OJZ/c/bWrdKi0yvKB/GIHl7fwJiaffi4b/eLbhlCg9DpHIU46C1dGkKoWpq4dGBZx2r11cyWy/LJGcIAVJeSmxZXog9GcZuB143abQElXvsMM8UO1OwQxHaQ8BNYdC+RDd2roO8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
